export const professionalAreas: Record<string, string[]> = {
    'Information Technology': [
        'Software Engineer',
        'Project Manager',
        'Network Administrator',
        'Database Administrator',
        'IT Support Specialist',
        'Web Developer',
        'Cybersecurity Analyst',
        'DevOps Engineer',
        'Cloud Architect',
        'Data Scientist',
    ],
    Engineering: [
        'Civil Engineer',
        'Mechanical Engineer',
        'Electrical Engineer',
        'Chemical Engineer',
        'Industrial Engineer',
        'Software Engineer',
        'Environmental Engineer',
        'Aerospace Engineer',
        'Biomedical Engineer',
        'Nuclear Engineer',
    ],
    Healthcare: [
        'Registered Nurse',
        'Physician Assistant',
        'Medical Laboratory Technologist',
        'Radiologic Technologist',
        'Physical Therapist',
        'Occupational Therapist',
        'Respiratory Therapist',
        'Pharmacist',
        'Dietitian',
        'Medical Social Worker',
    ],
    Finance: [
        'Accountant',
        'Financial Analyst',
        'Auditor',
        'Tax Advisor',
        'Investment Banker',
        'Credit Analyst',
        'Financial Planner',
        'Loan Officer',
        'Budget Analyst',
        'Risk Manager',
    ],
    Education: [
        'Primary School Teacher',
        'Secondary School Teacher',
        'Special Education Teacher',
        'School Counselor',
        'Educational Administrator',
        'Librarian',
        'Curriculum Developer',
        'Instructional Coordinator',
        'College Professor',
        'Training and Development Specialist',
    ],
    Marketing: [
        'Marketing Manager',
        'Digital Marketing Specialist',
        'SEO Specialist',
        'Content Strategist',
        'Brand Manager',
        'Market Research Analyst',
        'Public Relations Specialist',
        'Social Media Manager',
        'Advertising Manager',
        'Product Marketing Manager',
    ],
    Sales: [
        'Sales Manager',
        'Account Executive',
        'Retail Sales Associate',
        'Sales Representative',
        'Business Development Manager',
        'Inside Sales Representative',
        'Outside Sales Representative',
        'Sales Consultant',
        'Sales Engineer',
        'Customer Success Manager',
    ],
    'Human Resources': [
        'HR Manager',
        'Recruitment Specialist',
        'HR Generalist',
        'Training and Development Coordinator',
        'Compensation and Benefits Specialist',
        'Employee Relations Specialist',
        'HR Analyst',
        'HR Assistant',
        'Talent Acquisition Specialist',
        'HR Director',
    ],
    Hospitality: [
        'Hotel Manager',
        'Front Desk Clerk',
        'Housekeeper',
        'Event Planner',
        'Food and Beverage Manager',
        'Concierge',
        'Guest Services Manager',
        'Reservation Agent',
        'Banquet Manager',
        'Executive Chef',
    ],
    Construction: [
        'Project Manager',
        'Site Engineer',
        'Construction Laborer',
        'Estimator',
        'Safety Manager',
        'Mason',
        'Electrician',
        'Plumber',
        'Carpenter',
        'Surveyor',
    ],
};
